name: Build & Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Build React frontend
      run: |
        cd .
        npm install
        npm run build
    - name: List files after build
      run: |
        echo "=== root ==="
        ls -lA .
        echo "=== dist dir ==="
        ls -lA dist || true
        echo "=== api dir ==="
        ls -lA api  || true

    - name: Copy dist and server to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port: 22
        source:   "dist/**,api/**,package.json,ecosystem.config.js"
        target: ~/founder-match

    - name: Deploy on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port: 22
        script: |
          cd ~/founder-match
          npm install --production
          pm2 reload ecosystem.config.js
          sudo systemctl reload nginx
# edit to run the pipeline
